@startuml
note "原型模式" as title

class Prototype{
    clone()
}
class ConcretePrototype1{
    clone()
}
class ConcretePrototype2{
    clone()
}

Prototype <|-- ConcretePrototype1
Prototype <|-- ConcretePrototype2

Client "prototype"..> Prototype

@enduml